app:
  serviceName: "invosync"
  host: "127.0.0.1"
  port: 8090
db:
  name: footem
  schema: "public"
  user: postgres
  host: "localhost"
  password: "@Bonny264"
  port: 5432
  logMode: true
  sslMode: "disable"
  migrationPath: "./scripts"
  connectionPool:
    maxOpenConnections: 30
    maxIdleConnections: 10
    maxIdleTime: 30
    maxLifeTime: 3600
    timeout: 30